# -*- coding: utf-8 -*-
"""MA323_Lab01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_mq48IfTUMkacePJgzpAhozIWiQfdpj
"""

a = 6; b = 0; m = 11
for xo in range(0,11):
  x = xo;ulist = [xo/m];y = -1;
  while(y != xo):
    y = (a*x + b)%m
    x = y
    ulist.append(y/m)
  del ulist[len(ulist) - 1]
  print(ulist)

a = 3; b = 0; m = 11
for xo in range(0,11):
  x = xo;ulist = [xo/m];y = -1
  while(y != xo):
    y = (a*x + b)%m
    x = y
    ulist.append(y/m)
  del ulist[len(ulist) - 1]
  print(ulist)

import matplotlib.pyplot as plt
import math

def LCG(a,b,m,seed):
  x = seed;y = 0;ulist = [x/m];freq = []
  for i in range(0,20):
    freq.append(0)
  while(y != seed):
    y = (a*x + b)%m
    x = y
    ulist.append(y/m)
    freq[math.floor(20 * y/m)] = 1 + freq[math.floor(20 * y/m)]
  print("Starting value of x is",xo)
  print("Frequency Array :");print(freq)
  plt.hist(ulist,bins = 20,rwidth = 0.75)
  print("Frequency Histogram : ")
  plt.show()

m = 244944;a = 1597;b = 20
arr = [1,29,391,15243,200001]
print("For a =",a,",b =",b,",m =",m)
for xo in arr:
  LCG(a,b,m,xo)
a = 51749
print("For a =",a,",b =",b,",m =",m)
for xo in arr:
  LCG(a,b,m,xo)

import matplotlib.pyplot as plt
a = 1229; b = 1; m = 2048;x = 1;y = 0;ulist = [1/m];vlist = [] 
while(y != 1):
  y = (a*x + b)%m
  x = y
  ulist.append(y/m)
  vlist.append(y/m)
del ulist[len(ulist) - 1]
plt.scatter(ulist,vlist)
plt.axis([0, 1, 0, 1])
plt.show()