# -*- coding: utf-8 -*-
"""MA323_Lab10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13RmCFNGECdE6oBY3hgnp9nAykV1Hhr58
"""

import matplotlib.pyplot as plt
import numpy as np
import statistics
import random
import math
import time
 
M_list = [100,1000,10000,100000]

print("Without using Antithetic variables:\n")

lengths1 = []

for M in M_list:
    print("\nSample size is ",M,"\n")
    U_list = []
    for i in range(M):
        U = np.random.uniform(0,1)
        U_list.append(math.exp(math.sqrt(U)))
    mean = statistics.mean(U_list)
    variance = statistics.variance(U_list)
    print("Mean of the sample is ",mean,"\n")
    print("Variance of the sample is ",variance,"\n")
    print("The 95% confidence interval is [",mean - 1.96 * math.sqrt(variance/M),",",mean + 1.96 * math.sqrt(variance/M),"]\n")
    lengths1.append(2*1.96*math.sqrt(variance/M))

print("\n\nWith using Antithetic variables:\n")

lengths2 = []

for M in M_list:
    print("\nSample size is ",M,"\n")
    U_list = []
    for i in range(M):
        U = np.random.uniform(0,1)
        U_list.append((math.exp(math.sqrt(U)) + math.exp(math.sqrt(1-U)))/2)
    mean = statistics.mean(U_list)
    variance = statistics.variance(U_list)
    print("Mean of the sample is ",mean,"\n")
    print("Variance of the sample is ",variance,"\n")
    print("The 95% confidence interval is [",mean - 1.96 * math.sqrt(variance/M),",",mean + 1.96 * math.sqrt(variance/M),"]\n")
    lengths2.append(2*1.96*math.sqrt(variance/M))

print("\nRatios of the lengths for the 95% confidence intervals are\n")
for i in range(4):
    print("For sample size = ",10 ** (2 + i),"the ratio is",lengths1[i]/lengths2[i],"\n")