# -*- coding: utf-8 -*-
"""MA323_Lab11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQFzbwxG0Nq38gx3Bgha9VTmTSpjOKxw
"""

import matplotlib.pyplot as plt
import numpy as np
import statistics
import random
import math
import time
 
N_list = [10,20,50,100]

n = 10000

for N in N_list:
    print("\nNumber of sub-intervals is ",N,"\n")
    u_list = []
    x = 15243;m = 244944;a = 1597;b = 20
    y = 0;freq = []
    for i in range(N):
        freq.append(0)
    for i in range(10000):
        y = (a*x + b)%m
        x = y
        u_list.append(y/m)
        freq[math.floor(N * y/m)] = 1 + freq[math.floor(N * y/m)]  
    disc = 0
    for i in range(N):
        disc = max(disc,abs(freq[i]/n - 1/N))
    print("The discrepancy is ",disc,"\n")